name: Run Unit Tests

on:
  push:
    branches:
      - '**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    env:
      EPMT_GUI_MOCK: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements-ui.txt.py3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ui.txt.py3

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run unit tests
        run: |
          python -m unittest test/test_urlparse.py test/test_boxplot.py test/test_selenium.py
